package com.joshlong.jukebox2.model;
// Generated Apr 5, 2010 1:20:15 AM by Hibernate Tools 3.2.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * CompactDisc generated by hbm2java
 */
@Entity
@Table(name = "compact_disc"
        , schema = "public"
)
public class CompactDisc implements java.io.Serializable {

    private long id;
    private String title;
    private float totalDuration;
    private String musicBrainzId;
    private String cddb2Query;
    private String genre;
    private double revision;
    private String cleanTitle;
    private String extension;
    private int year;
    private String category;
    private boolean ready;
    private Set<Track> tracks = new HashSet<Track>(0);

    public CompactDisc() {
    }

    public CompactDisc(long id,
                       String title,
                       float totalDuration,
                       String musicBrainzId,
                       String cddb2Query,
                       String genre,
                       double revision,
                       String cleanTitle,
                       String extension,
                       int year,
                       String category,
                       boolean ready) {
        this.id = id;
        this.title = title;
        this.totalDuration = totalDuration;
        this.musicBrainzId = musicBrainzId;
        this.cddb2Query = cddb2Query;
        this.genre = genre;
        this.revision = revision;
        this.cleanTitle = cleanTitle;
        this.extension = extension;
        this.year = year;
        this.category = category;
        this.ready = ready;
    }

    public CompactDisc(long id,
                       String title,
                       float totalDuration,
                       String musicBrainzId,
                       String cddb2Query,
                       String genre,
                       double revision,
                       String cleanTitle,
                       String extension,
                       int year,
                       String category,
                       boolean ready,
                       Set<Track> tracks) {
        this.id = id;
        this.title = title;
        this.totalDuration = totalDuration;
        this.musicBrainzId = musicBrainzId;
        this.cddb2Query = cddb2Query;
        this.genre = genre;
        this.revision = revision;
        this.cleanTitle = cleanTitle;
        this.extension = extension;
        this.year = year;
        this.category = category;
        this.ready = ready;
        this.tracks = tracks;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "title", nullable = false, length = 250)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "total_duration", nullable = false, precision = 8, scale = 8)
    public float getTotalDuration() {
        return this.totalDuration;
    }

    public void setTotalDuration(float totalDuration) {
        this.totalDuration = totalDuration;
    }

    @Column(name = "music_brainz_id", nullable = false, length = 200)
    public String getMusicBrainzId() {
        return this.musicBrainzId;
    }

    public void setMusicBrainzId(String musicBrainzId) {
        this.musicBrainzId = musicBrainzId;
    }

    @Column(name = "cddb2_query", nullable = false)
    public String getCddb2Query() {
        return this.cddb2Query;
    }

    public void setCddb2Query(String cddb2Query) {
        this.cddb2Query = cddb2Query;
    }

    @Column(name = "genre", nullable = false)
    public String getGenre() {
        return this.genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    @Column(name = "revision", nullable = false, precision = 17, scale = 17)
    public double getRevision() {
        return this.revision;
    }

    public void setRevision(double revision) {
        this.revision = revision;
    }

    @Column(name = "clean_title", nullable = false)
    public String getCleanTitle() {
        return this.cleanTitle;
    }

    public void setCleanTitle(String cleanTitle) {
        this.cleanTitle = cleanTitle;
    }

    @Column(name = "extension", nullable = false)
    public String getExtension() {
        return this.extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    @Column(name = "year", nullable = false)
    public int getYear() {
        return this.year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    @Column(name = "category", nullable = false, length = 10)
    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    @Column(name = "ready", nullable = false)
    public boolean isReady() {
        return this.ready;
    }

    public void setReady(boolean ready) {
        this.ready = ready;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "compactDisc")
    public Set<Track> getTracks() {
        return this.tracks;
    }

    public void setTracks(Set<Track> tracks) {
        this.tracks = tracks;
    }

}


