package com.joshlong.jukebox2.model;
// Generated Apr 5, 2010 1:20:15 AM by Hibernate Tools 3.2.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ManagedFile generated by hbm2java
 */
@Entity
@Table(name="managed_file"
    ,schema="public"
)
public class ManagedFile  implements java.io.Serializable {


     private long id;
     private UploadBundle uploadBundle;
     private StorageNode storageNode;
     private String extension;
     private double byteSize;
     private String originalFileName;
     private boolean ready;
     private String mountPrefix;
     private int priority;

    public ManagedFile() {
    }

	
    public ManagedFile(long id, String extension, double byteSize, String originalFileName, boolean ready, String mountPrefix, int priority) {
        this.id = id;
        this.extension = extension;
        this.byteSize = byteSize;
        this.originalFileName = originalFileName;
        this.ready = ready;
        this.mountPrefix = mountPrefix;
        this.priority = priority;
    }
    public ManagedFile(long id, UploadBundle uploadBundle, StorageNode storageNode, String extension, double byteSize, String originalFileName, boolean ready, String mountPrefix, int priority) {
       this.id = id;
       this.uploadBundle = uploadBundle;
       this.storageNode = storageNode;
       this.extension = extension;
       this.byteSize = byteSize;
       this.originalFileName = originalFileName;
       this.ready = ready;
       this.mountPrefix = mountPrefix;
       this.priority = priority;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="upload_bundle_id")
    public UploadBundle getUploadBundle() {
        return this.uploadBundle;
    }
    
    public void setUploadBundle(UploadBundle uploadBundle) {
        this.uploadBundle = uploadBundle;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="storage_node_id")
    public StorageNode getStorageNode() {
        return this.storageNode;
    }
    
    public void setStorageNode(StorageNode storageNode) {
        this.storageNode = storageNode;
    }
    
    @Column(name="extension", nullable=false, length=10)
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }
    
    @Column(name="byte_size", nullable=false, precision=17, scale=17)
    public double getByteSize() {
        return this.byteSize;
    }
    
    public void setByteSize(double byteSize) {
        this.byteSize = byteSize;
    }
    
    @Column(name="original_file_name", nullable=false)
    public String getOriginalFileName() {
        return this.originalFileName;
    }
    
    public void setOriginalFileName(String originalFileName) {
        this.originalFileName = originalFileName;
    }
    
    @Column(name="ready", nullable=false)
    public boolean isReady() {
        return this.ready;
    }
    
    public void setReady(boolean ready) {
        this.ready = ready;
    }
    
    @Column(name="mount_prefix", nullable=false, length=10)
    public String getMountPrefix() {
        return this.mountPrefix;
    }
    
    public void setMountPrefix(String mountPrefix) {
        this.mountPrefix = mountPrefix;
    }
    
    @Column(name="priority", nullable=false)
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }




}


