package com.joshlong.jukebox2.model;
// Generated Apr 5, 2010 1:20:15 AM by Hibernate Tools 3.2.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PerformanceGroup generated by hbm2java
 */
@Entity
@Table(name="performance_group"
    ,schema="public"
)
public class PerformanceGroup  implements java.io.Serializable {


     private long id;
     private String name;
     private String nameSoundex;
     private Set<PerformanceGroupAffiliation> performanceGroupAffiliations = new HashSet<PerformanceGroupAffiliation>(0);

    public PerformanceGroup() {
    }

	
    public PerformanceGroup(long id, String name, String nameSoundex) {
        this.id = id;
        this.name = name;
        this.nameSoundex = nameSoundex;
    }
    public PerformanceGroup(long id, String name, String nameSoundex, Set<PerformanceGroupAffiliation> performanceGroupAffiliations) {
       this.id = id;
       this.name = name;
       this.nameSoundex = nameSoundex;
       this.performanceGroupAffiliations = performanceGroupAffiliations;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="name_soundex", nullable=false)
    public String getNameSoundex() {
        return this.nameSoundex;
    }
    
    public void setNameSoundex(String nameSoundex) {
        this.nameSoundex = nameSoundex;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="performanceGroup")
    public Set<PerformanceGroupAffiliation> getPerformanceGroupAffiliations() {
        return this.performanceGroupAffiliations;
    }
    
    public void setPerformanceGroupAffiliations(Set<PerformanceGroupAffiliation> performanceGroupAffiliations) {
        this.performanceGroupAffiliations = performanceGroupAffiliations;
    }




}


