package com.joshlong.jukebox2.model;
// Generated Apr 5, 2010 1:20:15 AM by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerformanceGroupAffiliation generated by hbm2java
 */
@Entity
@Table(name="performance_group_affiliation"
    ,schema="public"
)
public class PerformanceGroupAffiliation  implements java.io.Serializable {


     private long id;
     private Performer performer;
     private PerformanceGroup performanceGroup;
     private Date start;
     private Date stop;

    public PerformanceGroupAffiliation() {
    }

	
    public PerformanceGroupAffiliation(long id, Performer performer, PerformanceGroup performanceGroup) {
        this.id = id;
        this.performer = performer;
        this.performanceGroup = performanceGroup;
    }
    public PerformanceGroupAffiliation(long id, Performer performer, PerformanceGroup performanceGroup, Date start, Date stop) {
       this.id = id;
       this.performer = performer;
       this.performanceGroup = performanceGroup;
       this.start = start;
       this.stop = stop;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="performer_id", nullable=false)
    public Performer getPerformer() {
        return this.performer;
    }
    
    public void setPerformer(Performer performer) {
        this.performer = performer;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="performance_group_id", nullable=false)
    public PerformanceGroup getPerformanceGroup() {
        return this.performanceGroup;
    }
    
    public void setPerformanceGroup(PerformanceGroup performanceGroup) {
        this.performanceGroup = performanceGroup;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="start", length=13)
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="stop", length=13)
    public Date getStop() {
        return this.stop;
    }
    
    public void setStop(Date stop) {
        this.stop = stop;
    }




}


