package com.joshlong.jukebox2.model;
// Generated Apr 5, 2010 1:20:15 AM by Hibernate Tools 3.2.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StorageNode generated by hbm2java
 */
@Entity
@Table(name="storage_node"
    ,schema="public"
)
public class StorageNode  implements java.io.Serializable {


     private long id;
     private int priority;
     private boolean offline;
     private boolean ready;
     private double bytesUsed;
     private String mountPrefix;
     private double totalByteCapacity;
     private Set<ManagedFile> managedFiles = new HashSet<ManagedFile>(0);

    public StorageNode() {
    }

	
    public StorageNode(long id, int priority, boolean offline, boolean ready, double bytesUsed, String mountPrefix, double totalByteCapacity) {
        this.id = id;
        this.priority = priority;
        this.offline = offline;
        this.ready = ready;
        this.bytesUsed = bytesUsed;
        this.mountPrefix = mountPrefix;
        this.totalByteCapacity = totalByteCapacity;
    }
    public StorageNode(long id, int priority, boolean offline, boolean ready, double bytesUsed, String mountPrefix, double totalByteCapacity, Set<ManagedFile> managedFiles) {
       this.id = id;
       this.priority = priority;
       this.offline = offline;
       this.ready = ready;
       this.bytesUsed = bytesUsed;
       this.mountPrefix = mountPrefix;
       this.totalByteCapacity = totalByteCapacity;
       this.managedFiles = managedFiles;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="priority", nullable=false)
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }
    
    @Column(name="offline", nullable=false)
    public boolean isOffline() {
        return this.offline;
    }
    
    public void setOffline(boolean offline) {
        this.offline = offline;
    }
    
    @Column(name="ready", nullable=false)
    public boolean isReady() {
        return this.ready;
    }
    
    public void setReady(boolean ready) {
        this.ready = ready;
    }
    
    @Column(name="bytes_used", nullable=false, precision=17, scale=17)
    public double getBytesUsed() {
        return this.bytesUsed;
    }
    
    public void setBytesUsed(double bytesUsed) {
        this.bytesUsed = bytesUsed;
    }
    
    @Column(name="mount_prefix", nullable=false, length=10)
    public String getMountPrefix() {
        return this.mountPrefix;
    }
    
    public void setMountPrefix(String mountPrefix) {
        this.mountPrefix = mountPrefix;
    }
    
    @Column(name="total_byte_capacity", nullable=false, precision=17, scale=17)
    public double getTotalByteCapacity() {
        return this.totalByteCapacity;
    }
    
    public void setTotalByteCapacity(double totalByteCapacity) {
        this.totalByteCapacity = totalByteCapacity;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="storageNode")
    public Set<ManagedFile> getManagedFiles() {
        return this.managedFiles;
    }
    
    public void setManagedFiles(Set<ManagedFile> managedFiles) {
        this.managedFiles = managedFiles;
    }




}


