package com.joshlong.jukebox2.model;
// Generated Apr 5, 2010 1:20:15 AM by Hibernate Tools 3.2.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SystemUser generated by hbm2java
 */
@Entity
@Table(name="system_user"
    ,schema="public"
)
public class SystemUser  implements java.io.Serializable {


     private long id;
     private Set<UserCredentials> userCredentialses = new HashSet<UserCredentials>(0);

    public SystemUser() {
    }

	
    public SystemUser(long id) {
        this.id = id;
    }
    public SystemUser(long id, Set<UserCredentials> userCredentialses) {
       this.id = id;
       this.userCredentialses = userCredentialses;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="systemUser")
    public Set<UserCredentials> getUserCredentialses() {
        return this.userCredentialses;
    }
    
    public void setUserCredentialses(Set<UserCredentials> userCredentialses) {
        this.userCredentialses = userCredentialses;
    }




}


