package com.joshlong.jukebox2.model;
// Generated Apr 5, 2010 1:20:15 AM by Hibernate Tools 3.2.0.CR1

import javax.persistence.*;

/**
 * Track generated by hbm2java
 */
@Entity
@Table(name = "track"
        , schema = "public"
)
public class Track implements java.io.Serializable {

    private long id;
    private CompactDisc compactDisc;
    private String title;
    private float duration;
    private int trackNo;
    private String titleSoundex;

    public Track() {
    }

    public Track(long id, CompactDisc compactDisc, String title, float duration, int trackNo, String titleSoundex) {
        this.id = id;
        this.compactDisc = compactDisc;
        this.title = title;
        this.duration = duration;
        this.trackNo = trackNo;
        this.titleSoundex = titleSoundex;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "compact_disc_id", nullable = false)
    public CompactDisc getCompactDisc() {
        return this.compactDisc;
    }

    public void setCompactDisc(CompactDisc compactDisc) {
        this.compactDisc = compactDisc;
    }

    @Column(name = "title", nullable = false)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "duration", nullable = false, precision = 8, scale = 8)
    public float getDuration() {
        return this.duration;
    }

    public void setDuration(float duration) {
        this.duration = duration;
    }

    @Column(name = "track_no", nullable = false)
    public int getTrackNo() {
        return this.trackNo;
    }

    public void setTrackNo(int trackNo) {
        this.trackNo = trackNo;
    }

    @Column(name = "title_soundex", nullable = false)
    public String getTitleSoundex() {
        return this.titleSoundex;
    }

    public void setTitleSoundex(String titleSoundex) {
        this.titleSoundex = titleSoundex;
    }

}


