package com.joshlong.jukebox2.model;
// Generated Apr 5, 2010 1:20:15 AM by Hibernate Tools 3.2.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UploadBundle generated by hbm2java
 */
@Entity
@Table(name="upload_bundle"
    ,schema="public"
)
public class UploadBundle  implements java.io.Serializable {


     private long id;
     private String name;
     private long userCredentialsId;
     private String status;
     private Set<ManagedFile> managedFiles = new HashSet<ManagedFile>(0);

    public UploadBundle() {
    }

	
    public UploadBundle(long id, String name, long userCredentialsId, String status) {
        this.id = id;
        this.name = name;
        this.userCredentialsId = userCredentialsId;
        this.status = status;
    }
    public UploadBundle(long id, String name, long userCredentialsId, String status, Set<ManagedFile> managedFiles) {
       this.id = id;
       this.name = name;
       this.userCredentialsId = userCredentialsId;
       this.status = status;
       this.managedFiles = managedFiles;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="user_credentials_id", nullable=false)
    public long getUserCredentialsId() {
        return this.userCredentialsId;
    }
    
    public void setUserCredentialsId(long userCredentialsId) {
        this.userCredentialsId = userCredentialsId;
    }
    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="uploadBundle")
    public Set<ManagedFile> getManagedFiles() {
        return this.managedFiles;
    }
    
    public void setManagedFiles(Set<ManagedFile> managedFiles) {
        this.managedFiles = managedFiles;
    }




}


