package com.joshlong.jukebox2.model;
// Generated Apr 5, 2010 1:20:15 AM by Hibernate Tools 3.2.0.CR1

import javax.persistence.*;

/**
 * UserCredentials generated by hbm2java
 */
@Entity
@Table(name = "user_credentials"
        , schema = "public"
)
public class UserCredentials implements java.io.Serializable {

    private long id;
    private SystemUser systemUser;
    private SiteAdmin siteAdmin;
    private String firstName;
    private String lastName;
    private String email;
    private String passphrase;
    private boolean active;
    private String userName;
    private boolean provideFtpAccount;

    public UserCredentials() {
    }

    public UserCredentials(long id,
                           String firstName,
                           String lastName,
                           String email,
                           String passphrase,
                           boolean active,
                           String userName,
                           boolean provideFtpAccount) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.passphrase = passphrase;
        this.active = active;
        this.userName = userName;
        this.provideFtpAccount = provideFtpAccount;
    }

    public UserCredentials(long id,
                           SystemUser systemUser,
                           SiteAdmin siteAdmin,
                           String firstName,
                           String lastName,
                           String email,
                           String passphrase,
                           boolean active,
                           String userName,
                           boolean provideFtpAccount) {
        this.id = id;
        this.systemUser = systemUser;
        this.siteAdmin = siteAdmin;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.passphrase = passphrase;
        this.active = active;
        this.userName = userName;
        this.provideFtpAccount = provideFtpAccount;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "system_user_id")
    public SystemUser getSystemUser() {
        return this.systemUser;
    }

    public void setSystemUser(SystemUser systemUser) {
        this.systemUser = systemUser;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "site_admin_id")
    public SiteAdmin getSiteAdmin() {
        return this.siteAdmin;
    }

    public void setSiteAdmin(SiteAdmin siteAdmin) {
        this.siteAdmin = siteAdmin;
    }

    @Column(name = "first_name", nullable = false)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "last_name", nullable = false)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "email", nullable = false)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "passphrase", nullable = false)
    public String getPassphrase() {
        return this.passphrase;
    }

    public void setPassphrase(String passphrase) {
        this.passphrase = passphrase;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    @Column(name = "user_name", nullable = false)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "provide_ftp_account", nullable = false)
    public boolean isProvideFtpAccount() {
        return this.provideFtpAccount;
    }

    public void setProvideFtpAccount(boolean provideFtpAccount) {
        this.provideFtpAccount = provideFtpAccount;
    }

}


